routes/web.php
<?php

Route::middleware(['web', 'auth'])
    ->namespace('Rapture\Users\Controllers')
    ->prefix('dashboard')
    ->name('dashboard.')
    ->group(function () {
        Route::resource('users', 'UsersController')->except('show', 'destroy');
        Route::resource('usergroups', 'UserGroupsController')->except('create', 'show', 'destroy');
        Route::get('impersonate/{user}', 'ImpersonateController@impersonate')->name('users.impersonate');
        Route::get('leave-impersonate', 'ImpersonateController@leaveImpersonate')->name('users.leave-impersonate');
    });

resources/views/dashboard/create.blade.php
<x-dashboard :title="langAction('new', __('users::package.singular'))">
    <x-heading class="flex justify-between items-center" :label="langAction('new', __('users::package.singular'))">
        <a href="{{ route('dashboard.users.index') }}">
            <em class="far fa-reply mr-2"></em> @lang('rapture::actions.return')
        </a>
    </x-heading>

    <x-container>
        <x-form method="post" action="{{ route('dashboard.users.store') }}">
            <div class="space-y-8">
                @hook('users.create.before')

                <x-form-section title="Personal Information">
                    <div class="sm:flex space-y-4 sm:space-y-0 sm:space-x-6">
                        <x-input name="name" label="First Name" class="flex-1" required />
                        <x-input name="lname" label="Last Name" class="flex-1" />
                    </div>

                    <x-input type="email" name="email" class="mt-4" :label="__('rapture::field.email')" required />

                    <x-combobox name="timezone" placeholder="- Select a timezone -" :options="$timezones" :value="auth()->user()->timezone ?? 'UTC'" label="Timezone" class="mt-4" />

                    @hook('users.create.personal')
                </x-form-section>

                @hook('users.create.between')

                <x-form-section title="Credentials" desc="Leave blank to have a password auto generated.">
                    <x-password :label="__('rapture::field.password')" />

                    <div class="relative flex items-start mt-6">
                        <div class="flex items-center h-5">
                            <x-checkbox id="sendCredentials" name="notify" value="yes" />
                        </div>
                        <div class="ml-3 text-sm leading-5">
                            <label for="sendCredentials">
                                <span class="font-medium text-gray-700 dark:text-slate-200">Email credentials</span>
                                <span class="block mt-1 text-gray-500 dark:text-slate-400">The user will receive an email with their username and password.</span>
                            </label>
                        </div>
                    </div>

                    @hook('users.create.credentials')
                </x-form-section>

                @if (count($groups) > 0)
                <x-form-section title="Groups" desc="Multiple groups may be applied." :wrap="false">
                    <div class="space-y-2">
                        @foreach ($groups as $group)
                            <x-box class="flex items-center justify-between">
                                <div>
                                    <p class="font-medium text-gray-900 dark:text-slate-200 cursor-pointer">{{ $group->name }}</p>
                                    @if ($group->description)
                                        <p class="text-sm text-gray-500 dark:text-slate-400 mt-1">{{ $group->description }}</p>
                                    @endif
                                </div>
                                <div class="flex-shrink-0">
                                    <x-toggle name="groups[]" value="{{ $group->id }}" />
                                </div>
                            </x-box>
                        @endforeach
                    </div>
                </x-form-section>
                @endif

                @hook('users.create.after')
            </div>

            <div class="mt-8 text-right">
                <x-button type="submit" size="large" color="primary">
                    @langAction('create', __('users::package.singular'))
                </x-button>
            </div>
        </x-form>
    </x-container>
</x-dashboard>

resources/views/dashboard/edit.blade.php
<x-dashboard :title="langAction('edit', __('users::package.singular'))">
    <x-heading class="flex justify-between items-center" :label="langAction('edit', __('users::package.singular'))">
        <a href="{{ route('dashboard.users.index') }}">
            <em class="far fa-reply mr-2"></em> @lang('rapture::actions.return')
        </a>
    </x-heading>

    <x-container>
        <x-form method="put" action="{{ route('dashboard.users.update', $user) }}">
            <div class="space-y-8">
                @hook('users.edit.before', compact('user'))

                <x-form-section title="Personal Information">
                    <div class="sm:flex space-y-4 sm:space-y-0 sm:space-x-6">
                        <x-input name="name" label="First Name" class="flex-1" :value="$user->name" required />
                        <x-input name="lname" label="Last Name" class="flex-1" :value="$user->lname" />
                    </div>

                    <x-input type="email" name="email" class="mt-4" :label="__('rapture::field.email')" required :value="$user->email" />

                    <x-combobox name="timezone" placeholder="- Select a timezone -" :options="$timezones" :value="$user->timezone ?? 'UTC'" label="Timezone" class="mt-4" />

                    @hook('users.edit.personal', compact('user'))
                </x-form-section>

                @hook('users.edit.between', compact('user'))

                <x-form-section title="Credentials" desc="Leave blank to keep the existing password.">
                    <x-password name="new_password" :label="__('rapture::field.password')" />

                    @hook('users.edit.credentials', compact('user'))
                </x-form-section>

                @if (count($groups) > 0)
                <x-form-section title="Groups" desc="Multiple groups may be applied." :wrap="false">
                    <div class="space-y-2">
                        @foreach ($groups as $group)
                            <x-box class="flex items-center justify-between">
                                <div>
                                    <p class="font-medium text-gray-900 dark:text-slate-200 cursor-pointer">{{ $group->name }}</p>
                                    @if ($group->description)
                                        <p class="text-sm text-gray-500 dark:text-slate-400 mt-1">{{ $group->description }}</p>
                                    @endif
                                </div>
                                <div class="flex-shrink-0">
                                    <x-toggle name="groups[]" value="{{ $group->id }}" :state="$userGroups->contains($group->id)" />
                                </div>
                            </x-box>
                        @endforeach
                    </div>
                </x-form-section>
                @endif

                @hook('users.edit.after', compact('user'))
            </div>

            <div class="mt-8 text-right">
                <x-button type="submit" size="large" color="primary">
                    @langAction('update', __('users::package.singular'))
                </x-button>
            </div>
        </x-form>
    </x-container>
</x-dashboard>

resources/views/dashboard/impersonate.blade.php
<x-button size="small" href="{{ route('dashboard.users.leave-impersonate') }}" outline>Exit Impersonation</x-button>

resources/views/dashboard/index.blade.php
<x-dashboard :title="__('users::package.plural')">
    <x-heading class="flex justify-between items-center" :label="__('users::package.plural')">
        @can('users.create', 'users')
            <x-button href="{{ route('dashboard.users.create') }}" color="primary" icon="user-plus">
                <span>@langAction('new', __('users::package.singular'))</span>
            </x-button>
        @endcan
    </x-heading>

    <livewire:user-table />
</x-dashboard>

resources/views/groups/edit.blade.php
<x-dashboard :title="langAction('edit', __('users::groups.singular'))">
    <x-heading class="flex justify-between items-center" :label="langAction('edit', __('users::groups.singular'))">
        <a href="{{ route('dashboard.usergroups.index') }}">
            <em class="far fa-reply mr-2"></em> @lang('rapture::actions.return')
        </a>
    </x-heading>

    <x-container>
        <x-form method="put" action="{{ route('dashboard.usergroups.update', $usergroup) }}">
            <div class="space-y-10">
                @hook('usergroups.edit.before', compact('usergroup'))

                <x-form-section title="Group Information">
                    <x-input name="name" :value="$usergroup->name" :label="__('rapture::field.name')" />

                    <x-textarea name="description" :value="$usergroup->description" rows="5" :label="__('users::groups.description')" class="mt-4" />
                </x-form-section>

                @hook('usergroups.edit.after', compact('usergroup'))
            </div>

            <div class="mt-8 text-right">
                <x-button type="submit" size="large" color="primary">
                    @langAction('update', __('users::groups.singular'))
                </x-button>
            </div>
        </x-form>
    </x-container>
</x-dashboard>

resources/views/groups/index.blade.php
<x-dashboard :title="__('users::groups.plural')">
    <x-heading class="flex justify-between items-center" :label="__('users::groups.plural')">
        @can('usergroups.create', 'groups')
            <x-quick-create :action="route('dashboard.usergroups.store')" icon="plus" :label="langAction('new', __('users::groups.singular'))" />
        @endcan
    </x-heading>

    <livewire:user-group-table />
</x-dashboard>